name: flutter_lazy_indexed_stack
description: A Flutter package that exposes an `IndexedStack` that can be lazily loaded.
version: 0.0.4
homepage: https://github.com/marcossevilla/lazy_indexed_stack
repository: https://github.com/marcossevilla/lazy_indexed_stack

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0
